/** Colors for native-only props (e.g. SymbolView.tintColor). Keep aligned with globals.css. */
export const colors = {
  background: '#fbfbf9',
  surface: '#ffffff',
  surfaceMuted: '#f7f6f2',
  text: '#0f172a',
  textSecondary: '#334155',
  textMuted: '#64748b',
  placeholder: '#94a3b8',
  border: '#e7e5df',
  divider: '#f1efe9',
  primary: '#3b5ee8',
  primaryPressed: '#2d4cd2',
  primaryLip: '#203db5',
  primarySoft: '#eef2ff',
  onPrimary: '#ffffff',
  success: '#10b981',
  successSoft: '#ecfdf5',
  successBorder: '#a7f3d0',
  successText: '#065f46',
  warning: '#f59e0b',
  warningSoft: '#fef3c7',
  warningBorder: '#fde68a',
  warningText: '#92400e',
  danger: '#f43f5e',
  dangerSoft: '#fff1f2',
  dangerBorder: '#fecdd3',
  dangerText: '#9f1239',
} as const;
